name: run tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
    tests:
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        - run: npm run cy:open
