name: run tests
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
    tests:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cypress info
          run: npx cypress info
        - name: Run tests
          uses: cypress-io/github-action@v4
          run: npm run cy:open
